# Helm parameters for grafana-operator installation. 
apiVersion: v2
name: grafana-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "v5.3.0"

dependencies:
- name: grafana-operator
  version: 0.1.1
  repository: oci://ghcr.io/grafana-operator/helm-charts
