apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  namespace: ch
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=false
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ch
  name: mypwds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/basic-auth
stringData:
  rootUser: 'root'
  rootHost: '%'
  rootPassword: 'sakila'
  #username: "root"
  #password: "sakila"

