apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: mypwds
type: kubernetes.io/basic-auth
stringData:
  rootUser: "root"
  rootHost: "%"
  rootPassword: "sakila"

