apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.25
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#apiVersion: mysql.oracle.com/v2
#kind: InnoDBCluster
#metadata:
#  name: mycluster
#  namespace: ch
#  annotations:
#    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=false
#    argocd.argoproj.io/sync-wave: "2"
#spec:
#  secretName: mypwds
#  tlsUseSelfSigned: true
#  instances: 1
#  router:
#    instances: 1
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: ch
#  name: mypwds
#  annotations:
#    argocd.argoproj.io/sync-wave: "1"
#type: kubernetes.io/basic-auth
#stringData:
#  rootUser: 'root'
#  rootHost: '%'
#  rootPassword: 'sakila'
#  #username: "root"
#  #password: "sakila"
#
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: mysql
#  namespace: ch
#spec:
#  destination:
#    namespace: ch
#    server: https://kubernetes.default.svc
#  project: default
#  source:
#    chart: mysql-operator
#    repoURL: https://helm-charts.bitpoke.io
#    targetRevision: 0.0.3
#  syncPolicy:
#    retry:
#      backoff:
#        duration: 5s
#        factor: 2
#        maxDuration: 3m0s
#      limit: 5
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true