apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator
    targetRevision: main
    path: bundle.yaml
    helm:
      values: |
        replicaCount: 2
        service:
          port: 8081
          targetPort: 8081
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}