apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-sink-connector-lightweight
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentvolume.hostPath }}