apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-sink-connector-lightweight
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi