apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    #namespace: default
    name: in-cluster
  project: default
  source:
    path: 'infra/prometheus-operator-crds'
    repoURL: https://github.com/Altinity/argocd-examples-clickhouse.git
    #targetRevision: '5146'
  syncPolicy:
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rbac
spec:
  destination:
    #namespace: default
    name: in-cluster
  project: default
  source:
    path: 'infra/prometheus-rbac'
    repoURL: https://github.com/Altinity/argocd-examples-clickhouse.git
    #targetRevision: '5146'
  syncPolicy:
    automated: {}