apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDataSource
metadata:
  name: clickhouse-datasource
spec:
  name: ${ENDPOINT}.yaml
  datasources:
    - name: "clickhouse"
      type: vertamedia-clickhouse-datasource
      access: proxy
      url: "http://clickhouse:8123
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        addCorsHeader: true
        defaultDatabase: "default"
        usePOST: true
        useYandexCloudAuthorization: true
