apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: clickhouse-datasource
spec:
  datasources:
    - name: "clickhouse"
      type: vertamedia-clickhouse-datasource
      access: proxy
      url: "http://clickhouse:8123"
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        addCorsHeader: true
        defaultDatabase: "default"