apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: clickhouse-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasources:
    - name: "clickhouse"
      type: vertamedia-clickhouse-datasource
      access: proxy
      url: "http://chendpoint-template-service:8123"
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        addCorsHeader: true
        defaultDatabase: "default"