apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend
  namespace: ch2
spec:
  generators:
  - git:
      repoURL: https://github.com/Altinity/argocd-examples-clickhouse
      revision: master
      directories:
      - path: clickhouse
      - path: zookeeper
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/Altinity/argocd-examples-clickhouse
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ch2
