---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: ch
stringData:
  GF_SECURITY_ADMIN_PASSWORD: admin
  GF_SECURITY_ADMIN_USER: admin
type: Opaque
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: ch
  labels:
    dashboards: "grafana"
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: GF_SECURITY_ADMIN_USER
                  name: credentials
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: GF_SECURITY_ADMIN_PASSWORD
                  name: credentials
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: ch
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
