## Prometheus operator podMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: clickhouse-metrics
  namespace: ch
  labels:
    app: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  namespaceSelector:
    matchNames:
      - test
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
  podMetricsEndpoints:
    - port: "metrics"

---

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  configuration:
    settings:
      # listen clickhosue-server embedded prometheus endpoint
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
      prometheus/status_info: true
    clusters:
      - name: "demo"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: server
          volumeClaimTemplate: storage
    users:
      root/networks/ip: "::/0"
      root/password: secretsecret
      root/profile: default
      root/access_management: 1
    files:
      query_log.xml: |
        <clickhouse>
          <query_log>
             <database>system</database>
             <table>query_log</table>
             <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
             <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          </query_log>
        </clickhouse>
    zookeeper: 
      nodes:
        - host: zookeeper
  templates:
    podTemplates:
      - name: pod-template-with-metrics
        metadata:
          # for `additionalScrapeConfigs`, look https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-template.yaml#L11
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9363"
      - name: server
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:22.3.15.34.altinitystable
            ports:
              - name: "metrics"
                containerPort: 9363
    volumeClaimTemplates:
      - name: storage
        # Do not delete PVC if installation is dropped.
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
