apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "argocd"
spec:
  configuration:
    clusters:
      - name: "demo"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: server
          volumeClaimTemplate: storage
    users:
      root/networks/ip: "::/0"
      root/password: secretsecret
      root/profile: default
      root/access_management: 1
    files:
      query_log.xml: |
        <clickhouse>
          <query_log>
             <database>system</database>
             <table>query_log</table>
             <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
             <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          </query_log>
        </clickhouse>
    zookeeper: 
      nodes:
        - host: zookeeper
  templates:
    podTemplates:
      - name: server
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:22.3.15.34.altinitystable
    volumeClaimTemplates:
      - name: storage
        # Do not delete PVC if installation is dropped.
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-service"
spec:
  defaults:
    templates:
      serviceTemplate: svc-template
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
  templates:
    serviceTemplates:
      - name: svc-template
        generateName: chendpoint-{chi}
        metadata:
          labels:
            custom.label: "custom.value"
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
