apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "argocd"
spec:
  configuration:
    clusters:
      - name: "demo"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: server
          volumeClaimTemplate: storage
    users:
      root/networks/ip: "::/0"
      root/password: secretsecret
      root/profile: default
      root/access_management: 1
    files:
      query_log.xml: |
        <clickhouse>
          <query_log>
             <database>system</database>
             <table>query_log</table>
             <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
             <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          </query_log>
        </clickhouse>
    zookeeper: 
      nodes:
        - host: keeper
  templates:
    podTemplates:
      - name: server
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.3.8.22.altinitystable
    volumeClaimTemplates:
      - name: storage
        # Do not delete PVC if installation is dropped.
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
